import { expect, test } from '@playwright/test';

test('공개 저장소 연결 → 실제 코드 분석 → 코멘트 → 검토 → Markdown 내보내기', async ({ page }, testInfo) => {
  test.skip(process.env.LIVE_GITHUB !== '1', '명시적으로 LIVE_GITHUB=1인 경우에만 GitHub에 접속합니다.');
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: /어떤 코드를/ })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('01-connect-desktop.png'), fullPage: true });
  await page.getByRole('button', { name: /지정한 예시 저장소 입력/ }).click();
  await page.getByRole('button', { name: '저장소 연결하기' }).click();
  await expect(page.getByRole('heading', { name: '어디까지 살펴볼까요?' })).toBeVisible({ timeout: 90_000 });
  await expect(page.locator('.scope-count strong')).not.toHaveText('0');
  await page.screenshot({ path: testInfo.outputPath('02-scope-desktop.png'), fullPage: true });
  await page.getByLabel('AI 상세 설명 함께 생성').uncheck();
  await page.getByRole('button', { name: '시스템 분석 시작' }).click();
  await expect(page.locator('.system-entry').first()).toBeVisible({ timeout: 120_000 });
  const machine = page.locator('.system-entry').filter({ hasText: /Machine/ }).first();
  if (await machine.count()) await machine.click();
  await expect(page.locator('.explanation-block').first()).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('03-workspace-desktop.png'), fullPage: true });
  await page.locator('.claim').first().locator('summary').click();
  await page.locator('.claim-sources .evidence-link').first().click();
  await expect(page.locator('.code-reference .code-lines')).toBeVisible();
  await expect(page.locator('.code-reference .code-line').first()).toContainText(/./);
  await page.getByLabel('근거 닫기').click();
  await page.getByLabel('코멘트 내용').fill('[UI 검증] 코멘트 저장 기능을 확인합니다. 실제 개발 의도에 관한 진술은 아닙니다.');
  await page.getByRole('button', { name: '코멘트 저장', exact: true }).click();
  await expect(page.locator('.comment-card')).toContainText('[UI 검증]');
  await page.getByRole('button', { name: '검토 완료', exact: true }).click();
  await expect(page.getByRole('button', { name: '검토 완료됨', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator('.system-entry').first()).toBeVisible();
  if (await machine.count()) await machine.click();
  await expect(page.locator('.comment-card')).toContainText('[UI 검증]');
  await page.getByRole('button', { name: '내보내기', exact: false }).first().click();
  await page.getByRole('button', { name: '내보내기 문서 만들기' }).click();
  await expect(page.locator('.export-preview pre')).toContainText('/blob/');
  await expect(page.locator('.export-preview pre')).toContainText('코드에서 확인한 구조');
  await page.screenshot({ path: testInfo.outputPath('04-export-desktop.png'), fullPage: true });
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Markdown 다운로드' }).click();
  await (await download).saveAs(testInfo.outputPath('retrospective.md'));
  await page.getByRole('button', { name: /시스템 회고/ }).click();
  await page.context().storageState({ path: '.runtime/e2e-session.json' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.comments-panel')).toBeVisible();
  const overflowing = await page.evaluate(() => [...document.querySelectorAll('body *')].filter(e => e.getBoundingClientRect().right > innerWidth + 1 && getComputedStyle(e).position !== 'absolute').map(e => ({ tag: e.tagName, class: e.className, right: e.getBoundingClientRect().right })).slice(0, 15));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), JSON.stringify(overflowing)).toBeTruthy();
  await page.screenshot({ path: testInfo.outputPath('05-workspace-mobile.png'), fullPage: true });
  expect(errors).toEqual([]);
});
