"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-09-17 00:31:08.234688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_budgets',
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('used_tokens', sa.Integer(), nullable=False),
    sa.Column('reserved_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('visitor_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('visitor_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_id', 'key')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('visitor_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('repo_owner', sa.String(length=100), nullable=False),
    sa.Column('repo_name', sa.String(length=100), nullable=False),
    sa.Column('github_username', sa.String(length=100), nullable=False),
    sa.Column('project_type', sa.String(length=20), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('current_run_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_visitor_id'), 'projects', ['visitor_id'], unique=False)
    op.create_table('config_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('selected_file_ids', sa.JSON(), nullable=False),
    sa.Column('classifications', sa.JSON(), nullable=False),
    sa.Column('attribution', sa.JSON(), nullable=False),
    sa.Column('github_username', sa.String(length=100), nullable=False),
    sa.Column('project_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version')
    )
    op.create_index(op.f('ix_config_versions_project_id'), 'config_versions', ['project_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('revision_ids', sa.JSON(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_project_id'), 'exports', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=200), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_token', sa.String(length=32), nullable=True),
    sa.Column('lease_until', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'available_at'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('tree_sha', sa.String(length=40), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_project_id'), 'snapshots', ['project_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('config_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['config_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_project_id'), 'analysis_runs', ['project_id'], unique=False)
    op.create_table('source_files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('blob_sha', sa.String(length=40), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('encoding', sa.String(length=30), nullable=True),
    sa.Column('parsed', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'path')
    )
    op.create_index(op.f('ix_source_files_snapshot_id'), 'source_files', ['snapshot_id'], unique=False)
    op.create_table('tool_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_runs_job_id'), 'tool_runs', ['job_id'], unique=False)
    op.create_table('systems',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('group_key', sa.String(length=500), nullable=False),
    sa.Column('file_ids', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('current_revision_id', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systems_run_id'), 'systems', ['run_id'], unique=False)
    op.create_table('explanation_revisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('config_id', sa.String(length=32), nullable=False),
    sa.Column('system_version', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('comment_ids', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['config_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'number')
    )
    op.create_index(op.f('ix_explanation_revisions_system_id'), 'explanation_revisions', ['system_id'], unique=False)
    op.create_table('comment_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('root_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('base_revision_id', sa.String(length=32), nullable=False),
    sa.Column('block_id', sa.String(length=150), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_revision_id'], ['explanation_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_id', 'version')
    )
    op.create_index(op.f('ix_comment_versions_root_id'), 'comment_versions', ['root_id'], unique=False)
    op.create_index(op.f('ix_comment_versions_system_id'), 'comment_versions', ['system_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_versions_system_id'), table_name='comment_versions')
    op.drop_index(op.f('ix_comment_versions_root_id'), table_name='comment_versions')
    op.drop_table('comment_versions')
    op.drop_index(op.f('ix_explanation_revisions_system_id'), table_name='explanation_revisions')
    op.drop_table('explanation_revisions')
    op.drop_index(op.f('ix_systems_run_id'), table_name='systems')
    op.drop_table('systems')
    op.drop_index(op.f('ix_tool_runs_job_id'), table_name='tool_runs')
    op.drop_table('tool_runs')
    op.drop_index(op.f('ix_source_files_snapshot_id'), table_name='source_files')
    op.drop_table('source_files')
    op.drop_index(op.f('ix_analysis_runs_project_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_snapshots_project_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_exports_project_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_config_versions_project_id'), table_name='config_versions')
    op.drop_table('config_versions')
    op.drop_index(op.f('ix_projects_visitor_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('idempotency_keys')
    op.drop_table('visitor_sessions')
    op.drop_table('ai_budgets')
    # ### end Alembic commands ###
