import { useState } from 'react';
import { Check, Copy, Download, FileText, Info } from 'lucide-react';
import { api, download } from './api';
import type { RunAction } from './App';
import type { Project, System } from './types';

export default function ExportPage({ project, systems, busy, run, notify }: { project: Project; systems: System[]; busy: boolean; run: RunAction; notify: (text: string) => void }) {
  const eligible = systems.filter(s => s.revision && !s.revision.stale);
  const [selected, setSelected] = useState(() => eligible.filter(s => s.revision?.reviewed).map(s => s.id));
  const [include, setInclude] = useState(false); const [output, setOutput] = useState(''); const [copied, setCopied] = useState(false);
  const invalid = selected.some(id => !eligible.find(s => s.id === id)?.revision?.reviewed);
  return <main className="export-page"><div className="page-heading"><div><span className="eyebrow">04 / YOUR DEVELOPMENT STORY</span><h1>정리한 내용을 가져가세요.</h1><p>상세 문단과 코드 근거를 그대로 담아 Markdown으로 내보냅니다.</p></div><FileText size={32} className="muted" /></div><div className="export-layout"><section className="export-options"><h2>포함할 시스템</h2><p className="muted">시스템별 최신 설명을 한 개씩 포함합니다.</p>{systems.map(s => <label className={`export-system ${s.revision?.stale ? 'disabled' : ''}`} key={s.id}><input type="checkbox" checked={selected.includes(s.id)} disabled={!s.revision || s.revision.stale || busy} onChange={e => { setSelected(old => e.target.checked ? [...old, s.id] : old.filter(id => id !== s.id)); setOutput(''); }} /><div><strong>{s.name}</strong><span>{s.revision?.stale ? '설정 변경됨 · 다시 분석 필요' : s.revision?.reviewed ? '검토 완료' : '미검토'} · v{s.revision?.number || 0}</span></div>{s.revision?.reviewed && <Check size={16} className="success-text" />}</label>)}<label className="checkbox-label export-unreviewed"><input type="checkbox" checked={include} onChange={e => { setInclude(e.target.checked); setOutput(''); }} />미검토 설명도 초안으로 포함</label><div className="hint"><Info size={17} /><span>코드 관찰 · 사용자 설명 · 추정을 구분하고, 고정된 커밋의 코드 링크를 함께 남깁니다.</span></div><button className="button primary full" disabled={busy || !selected.length || (invalid && !include)} onClick={() => void run(async () => { const result = await api<{ markdown: string }>(`/projects/${project.id}/exports`, 'POST', { revision_ids: selected.map(id => systems.find(s => s.id === id)!.revision!.id), include_unreviewed: include }); setOutput(result.markdown); })}><FileText size={16} />내보내기 문서 만들기</button></section><section className="export-preview"><div className="section-heading"><h2><FileText size={16} />Markdown 미리보기</h2><span className="tag">{output ? `${output.length.toLocaleString()}자` : '선택한 상세 문단 전체'}</span></div>{output ? <><pre>{output}</pre><div className="preview-actions"><button className="button" onClick={() => void run(async () => { await navigator.clipboard.writeText(output); setCopied(true); notify('상세 문단과 코드 근거를 복사했습니다.'); })}>{copied ? <Check size={15} /> : <Copy size={15} />}복사</button><button className="button primary" onClick={() => download(`${project.name.replace(/[<>:"/\\|?*]/g, '_')}-회고.md`, output)}><Download size={15} />Markdown 다운로드</button></div></> : <div className="export-empty"><FileText size={38} /><h3>설명을 선택하고 문서를 만들어보세요.</h3><p>요약만 추려내지 않고, 검토한 상세 내용을 그대로 담습니다.</p></div>}</section></div></main>;
}
