import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, ChevronRight, FileCode2, Filter, Folder, GitBranch, Info, RefreshCw, Save, Search, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { api } from './api';
import type { RunAction } from './App';
import { categoryLabels, ownershipLabels, type Job, type Ownership, type Project, type Scope, type SourceFile } from './types';

export default function ScopePage({ project, files, busy, aiEnabled, run, refresh, setJob }: { project: Project; files: SourceFile[]; busy: boolean; aiEnabled: boolean; run: RunAction; refresh: () => Promise<Project | undefined>; setJob: (job: Job) => void }) {
  const [scope, setScope] = useState<Scope>(project.scope);
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('all'); const [folder, setFolder] = useState(''); const [limit, setLimit] = useState(200);
  const [useAi, setUseAi] = useState(false); const [manual, setManual] = useState(false);
  const [inspected, setInspected] = useState<SourceFile | null>(null);
  useEffect(() => { setScope(project.scope); }, [project.config_version]);
  const selected = useMemo(() => new Set(scope.selected_file_ids), [scope.selected_file_ids]);
  const dirty = JSON.stringify(scope) !== JSON.stringify(project.scope);
  const folders = useMemo(() => [...new Set(files.map(f => f.path.split('/').slice(0, -1).join('/')))].sort(), [files]);
  const shown = files.filter(f => (!folder || f.path.startsWith(folder + '/')) && (category === 'all' || (category === 'selected' ? selected.has(f.id) : (scope.classifications[f.id] || f.category) === category)) && f.path.toLowerCase().includes(query.toLowerCase()));
  const size = files.filter(f => selected.has(f.id)).reduce((n, f) => n + f.size, 0);
  const canSelect = (f: SourceFile) => !['unsupported', 'oversize'].includes(f.category);
  const setSelected = (ids: string[], value: boolean) => setScope(old => ({ ...old, selected_file_ids: value ? [...new Set([...old.selected_file_ids, ...ids])] : old.selected_file_ids.filter(id => !ids.includes(id)) }));
  function ownership(ids: string[], status: Ownership['status']) {
    setScope(old => ({ ...old, attribution: { ...old.attribution, ...Object.fromEntries(ids.map(id => [id, { ...old.attribution[id], status, account: status === 'mine' ? project.github_username : old.attribution[id]?.account || '', note: old.attribution[id]?.note || '' }])) } }));
  }
  async function save() {
    if (!dirty) return project;
    const p = await api<Project>(`/projects/${project.id}/scope`, 'PUT', { ...scope, expected_version: project.config_version });
    await refresh(); return p;
  }
  const identityUnverified = !project.snapshot?.metadata.user_exists || project.snapshot.metadata.identity_checked.toLowerCase() !== project.github_username.toLowerCase();
  return <main className="scope-page"><div className="page-heading"><div><span className="eyebrow">02 / ANALYSIS SCOPE</span><h1>어디까지 살펴볼까요?</h1><p>프로젝트 코드와 외부 코드를 구분하고, 내가 개발한 범위를 표시해주세요.</p></div><button className="button subtle" disabled={busy} onClick={() => void run(async () => { const res = await api<{ job: Job }>(`/projects/${project.id}/snapshots`, 'POST', { expected_version: project.config_version, ref: project.ref }); setJob(res.job); })}><RefreshCw size={15} />저장소 다시 확인</button></div>
    <div className="repository-strip"><span className="square-icon"><Folder size={20} /></span><div><strong>{project.snapshot?.metadata.full_name}</strong><span><GitBranch size={12} />{project.snapshot?.ref}<code>{project.snapshot?.commit_sha.slice(0, 7)}</code></span></div><span className="repo-type"><Users size={14} />{project.project_type === 'team' ? '팀 프로젝트' : '개인 프로젝트'}</span><span className="tag">기준 계정 @{project.github_username}</span></div>
    {!project.snapshot?.coverage.tree_complete && <div className="inline-warning"><Info size={16} />저장소 파일 목록의 일부만 확인했습니다. 누락된 경로가 있을 수 있습니다.</div>}
    <div className="scope-layout"><aside className="scope-folders"><div className="panel-label">탐색기 <span>{files.length}</span></div><button className={!folder ? 'folder-entry active' : 'folder-entry'} onClick={() => setFolder('')}><Folder size={15} />전체 C# 파일</button><div className="folder-list">{folders.map(path => <button className={folder === path ? 'folder-entry active' : 'folder-entry'} key={path} title={path} onClick={() => setFolder(path)}><ChevronRight size={12} /><Folder size={14} /><span>{path.split('/').slice(-2).join('/')}</span><small>{files.filter(f => f.path.startsWith(path + '/')).length}</small></button>)}</div><div className="folder-note"><ShieldCheck size={17} /><p>프로젝트는 실행하지 않습니다.<br />선택한 C# 파일만 분석합니다.</p></div></aside>
      <section className="scope-files"><div className="scope-toolbar"><div className="search-field"><Search size={15} /><input aria-label="파일 검색" placeholder="파일 이름이나 경로 검색" value={query} onChange={e => { setQuery(e.target.value); setLimit(200); }} /></div><div className="select-filter"><Filter size={14} /><select aria-label="파일 분류 필터" value={category} onChange={e => { setCategory(e.target.value); setLimit(200); }}><option value="all">모든 분류</option><option value="selected">선택한 파일</option>{Object.entries(categoryLabels).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></div></div>
        <div className="selection-actions"><label className="checkbox-label"><input type="checkbox" aria-label="현재 표시된 파일 전체 선택" checked={shown.length > 0 && shown.filter(canSelect).every(f => selected.has(f.id))} disabled={busy} onChange={e => setSelected(shown.filter(canSelect).map(f => f.id), e.target.checked)} />표시된 파일</label><span>{shown.length}개</span><button className="text-button" disabled={busy} onClick={() => setScope(old => ({ ...old, selected_file_ids: files.filter(f => (scope.classifications[f.id] || f.category) === 'project' && canSelect(f)).map(f => f.id) }))}>프로젝트 코드만 선택</button></div>
        <div className="file-table-wrap"><table className="file-table"><thead><tr><th className="check-cell" /><th>파일</th><th>분류</th><th>담당 범위</th></tr></thead><tbody>{shown.slice(0, limit).map(f => <tr key={f.id} className={selected.has(f.id) ? 'selected' : ''}><td><input type="checkbox" aria-label={`${f.path} 선택`} checked={selected.has(f.id)} disabled={busy || !canSelect(f)} onChange={e => setSelected([f.id], e.target.checked)} /></td><td><button className="file-name" onClick={() => setInspected(f)}><FileCode2 size={16} /><span>{f.path.split('/').pop()}<small>{f.path.split('/').slice(0, -1).join('/')}</small></span></button>{f.error && <span className="file-error">{f.error}</span>}</td><td><select className="inline-select" aria-label={`${f.path} 분류`} disabled={busy || !canSelect(f)} value={scope.classifications[f.id] || f.category} onChange={e => setScope(old => ({ ...old, classifications: { ...old.classifications, [f.id]: e.target.value } }))}>{Object.entries(categoryLabels).filter(([key]) => canSelect(f) ? !['unsupported', 'oversize'].includes(key) : key === f.category).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></td><td><select className={`inline-select owner-${scope.attribution[f.id]?.status || 'unknown'}`} aria-label={`${f.path} 담당 범위`} disabled={busy} value={scope.attribution[f.id]?.status || 'unknown'} onChange={e => ownership([f.id], e.target.value as Ownership['status'])}>{Object.entries(ownershipLabels).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></td></tr>)}</tbody></table>{!shown.length && <div className="empty-state small"><Search size={24} /><p>조건에 맞는 C# 파일이 없습니다.</p></div>}{shown.length > limit && <button className="button subtle full" onClick={() => setLimit(limit + 200)}>파일 더 보기 ({shown.length - limit}개)</button>}</div>
        <div className="bulk-ownership"><span>선택한 {selected.size}개 담당 지정</span>{(['mine', 'shared', 'unknown'] as const).map(status => <button className="button small subtle" disabled={busy || !selected.size} key={status} onClick={() => ownership([...selected], status)}>{ownershipLabels[status]}</button>)}</div>
      </section>
      <aside className="scope-summary"><div className="panel-label">분석 준비</div><div className="scope-count"><strong>{selected.size}</strong><span>/ {files.length}개 파일 선택</span></div><div className="summary-line"><span>선택한 코드</span><strong>{(size / 1024).toFixed(0)} KB</strong></div><div className="summary-line"><span>내 코드로 지정</span><strong>{[...selected].filter(id => scope.attribution[id]?.status === 'mine').length}개</strong></div><div className="summary-line"><span>공동 작업</span><strong>{[...selected].filter(id => scope.attribution[id]?.status === 'shared').length}개</strong></div><hr /><div className="scope-tip"><Info size={17} /><h3>분류는 확인을 위한 초안이에요</h3><p>폴더·네임스페이스·스타일은 담당 구분의 힌트입니다. 같은 스타일을 쓴 사람이 여럿일 수도 있고, 한 사람이 여러 스타일을 썼을 수도 있습니다.</p></div>
        {inspected && <div className="file-inspector"><strong>{inspected.path.split('/').pop()}</strong><p>{inspected.reason}</p><span className="tag">{inspected.size.toLocaleString()} bytes</span>{inspected.namespaces.map(n => <code key={n}>{n}</code>)}{inspected.parse_errors && <p className="warning-text">구문 일부를 해석하지 못했습니다.</p>}<label>담당 메모<textarea rows={3} placeholder="함께 작업한 사람이나 구체적인 담당 부분" disabled={busy} value={scope.attribution[inspected.id]?.note || ''} onChange={e => setScope(old => ({ ...old, attribution: { ...old.attribution, [inspected.id]: { status: old.attribution[inspected.id]?.status || 'unknown', account: old.attribution[inspected.id]?.account || '', note: e.target.value } } }))} maxLength={2000} /></label></div>}
        <hr /><label className="checkbox-label ai-option"><input type="checkbox" checked={useAi} disabled={!aiEnabled || busy} onChange={e => setUseAi(e.target.checked)} /><Sparkles size={15} />AI 상세 설명 함께 생성</label>{!aiEnabled && <p className="micro-copy">AI 연결 전에는 파일 수집과 코드 구조 분석을 사용할 수 있습니다. 코멘트도 저장할 수 있습니다.</p>}{identityUnverified && <label className="checkbox-label manual-identity"><input type="checkbox" checked={manual} onChange={e => setManual(e.target.checked)} />계정 확인 없이 담당 범위를 직접 지정할게요.</label>}
      </aside></div>
    <div className="page-actionbar"><span>{dirty ? <><span className="unsaved-dot" />아직 저장하지 않은 변경 사항</> : <><Check size={15} />현재 설정이 저장되어 있습니다</>}</span><div><button className="button" disabled={busy || !dirty} onClick={() => void run(async () => { await save(); })}><Save size={15} />범위 저장</button><button className="button primary" disabled={busy || !selected.size || (identityUnverified && !manual)} onClick={() => void run(async () => { const p = await save(); const res = await api<{ job: Job }>(`/projects/${project.id}/analyses`, 'POST', { expected_version: p.config_version, use_ai: useAi, manual_identity: manual }); setJob(res.job); })}>시스템 분석 시작<ArrowRight size={16} /></button></div></div>
  </main>;
}
