import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCheck, ChevronRight, Code2, ExternalLink, FileCode2, GitCommitHorizontal, History, Info, Layers3, MessageSquare, Pencil, Plus, Search, Send, Sparkles, Users, X } from 'lucide-react';
import { api } from './api';
import type { RunAction } from './App';
import { ownershipLabels, type Code, type Comment, type Evidence, type Job, type Project, type Revision, type SourceFile, type System } from './types';

type Props = { project: Project; files: SourceFile[]; systems: System[]; busy: boolean; aiEnabled: boolean; run: RunAction; refresh: () => Promise<Project | undefined>; setJob: (job: Job) => void; notify: (text: string) => void };
const basisLabels: Record<string, string> = { code_observation: '코드에서 확인', history_observation: '이력에서 확인', user_statement: '사용자 설명', inference: '확인할 추정' };
const commentKinds: Record<string, string> = { general: '추가 설명', ownership: '내 담당 부분', intent: '개발 의도', emphasis: '강조할 점', correction: '내용 수정' };

export default function Workspace(props: Props) {
  const { project, files, systems, busy, aiEnabled, run, refresh, setJob, notify } = props;
  const [systemId, setSystemId] = useState(''); const [query, setQuery] = useState('');
  const system = systems.find(s => s.id === systemId) || systems[0];
  const [tab, setTab] = useState<'story' | 'code' | 'ownership'>('story');
  const [revisions, setRevisions] = useState<Revision[]>([]); const [revisionId, setRevisionId] = useState('');
  const [comments, setComments] = useState<Comment[]>([]); const [selected, setSelected] = useState<string[]>([]);
  const [comment, setComment] = useState(''); const [kind, setKind] = useState('general'); const [blockId, setBlockId] = useState('');
  const [code, setCode] = useState<Code | null>(null); const [reference, setReference] = useState<Evidence | null>(null);
  const [editComment, setEditComment] = useState<Comment | null>(null); const [editText, setEditText] = useState('');
  const [editSystem, setEditSystem] = useState(false);
  const [history, setHistory] = useState<{ sha: string; author_login: string | null; author_name: string; message: string; date: string }[]>([]);
  const draft = useRef<HTMLTextAreaElement>(null);
  const base = `/projects/${project.id}/systems/${system?.id}`;
  const revision = revisions.find(r => r.id === revisionId) || system?.revision || null;
  const members = files.filter(f => system?.file_ids.includes(f.id));
  useEffect(() => {
    let cancelled = false;
    setRevisions([]); setRevisionId(''); setComments([]); setSelected([]); setCode(null); setReference(null); setBlockId('');
    setEditComment(null);
    if (!system) return;
    void Promise.all([api<{ revisions: Revision[] }>(`${base}/revisions`), api<{ comments: Comment[] }>(`${base}/comments`)]).then(([r, c]) => { if (!cancelled) { setRevisions(r.revisions); setComments(c.comments); } }).catch(e => { if (!cancelled) notify(e instanceof Error ? e.message : '설명을 불러오지 못했습니다.'); });
    return () => { cancelled = true; };
  }, [system?.id, system?.revision?.id, system?.revision?.reviewed, project.config_version]);
  useEffect(() => {
    let cancelled = false;
    if (tab === 'ownership') void api<{ history: typeof history }>(`/projects/${project.id}/systems`).then(data => { if (!cancelled) setHistory(data.history); }).catch(() => { if (!cancelled) setHistory([]); });
    return () => { cancelled = true; };
  }, [tab, project.id]);
  useEffect(() => { setComment(''); setKind('general'); }, [system?.id]);
  const activeComments = comments.filter(c => c.base_revision_id === revision?.id);
  async function loadCode(fileId: string, start = 1, end = start + 119) { const data = await api<Code>(`/projects/${project.id}/files/${fileId}?start=${start}&end=${Math.min(end, start + 199)}`); setCode(data); }
  async function inspect(evidence: Evidence) {
    setReference(evidence);
    if (evidence.kind === 'code' && evidence.file_id) await loadCode(evidence.file_id, evidence.start_line || 1, Math.max(evidence.start_line || 1, Math.min(evidence.end_line || 120, (evidence.start_line || 1) + 119)));
  }
  const allowedIds = selected.filter(id => activeComments.some(c => c.id === id));
  const current = revision && !revision.stale && revision.id === system?.revision?.id;
  if (!system) return <div className="empty-state"><Layers3 size={30} /><h2>시스템 분석 결과가 아직 없습니다.</h2><p>분석 범위에서 C# 파일을 선택하고 분석을 시작해주세요.</p></div>;
  return <main className="workspace"><aside className="systems-sidebar"><div className="sidebar-heading"><h2><Layers3 size={15} />시스템</h2><span>{systems.length}</span></div><div className="search-field sidebar-search"><Search size={14} /><input aria-label="시스템 검색" placeholder="시스템 검색" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="system-list">{systems.filter(s => (s.name + s.group_key).toLowerCase().includes(query.toLowerCase())).map(s => <button className={`system-entry ${s.id === system.id ? 'active' : ''}`} key={s.id} title={s.group_key} onClick={() => { setSystemId(s.id); setTab('story'); }}><span className="system-icon"><Layers3 size={16} /></span><span><strong>{s.name}</strong><small>{s.file_ids.length}개 파일 · {s.revision?.reviewed ? '검토 완료' : s.revision?.source === 'ai' ? 'AI 초안' : '구조 메모'}</small></span>{s.revision?.reviewed ? <Check size={13} className="success-text" /> : <span className="system-dot" />}</button>)}</div><div className="sidebar-foot"><span className="eyebrow">검토 진행</span><div><strong>{systems.filter(s => s.revision?.reviewed && !s.revision.stale).length}</strong><span>/ {systems.length} 시스템</span></div><progress max={systems.length || 1} value={systems.filter(s => s.revision?.reviewed && !s.revision.stale).length} /><p>설명과 코드 근거를 살펴보고<br />검토 완료로 표시해주세요.</p></div></aside>
    <section className="workspace-main"><div className="workspace-breadcrumb"><span>{project.name}</span><ChevronRight size={12} /><span>{system.name}</span><span className="workspace-breadcrumb-right"><GitCommitHorizontal size={13} />{project.snapshot?.commit_sha.slice(0, 7)}</span></div><div className="system-heading"><div><div className="system-eyebrow"><span className="tag">SYSTEM</span>{revision && <span className={`review-state ${revision.reviewed ? 'done' : ''}`}>{revision.reviewed ? <CheckCheck size={13} /> : <span className="unsaved-dot" />}{revision.reviewed ? '검토 완료' : '검토 전'}</span>}</div><h1>{system.name}<button className="icon-button" title="시스템 이름·파일 소속 수정" aria-label="시스템 이름·파일 소속 수정" onClick={() => setEditSystem(true)} disabled={busy}><Pencil size={15} /></button></h1><p>{members.length}개 파일 <span>·</span> {system.summary.namespaces?.join(', ') || '네임스페이스 미지정'}</p></div><button className={`button small ${revision?.reviewed ? 'reviewed-button' : ''}`} disabled={busy || !current} onClick={() => void run(async () => { await api(`${base}/review`, 'PUT', { base_revision_id: revision!.id, reviewed: !revision!.reviewed }); await refresh(); notify(revision!.reviewed ? '검토 완료 표시를 해제했습니다.' : '검토 완료로 저장했습니다.'); })}><Check size={15} />{revision?.reviewed ? '검토 완료됨' : '검토 완료'}</button></div>
      <div className="workspace-tabs"><div>{([['story', '개발 회고', BookOpen], ['code', '관련 코드', Code2], ['ownership', '담당 힌트', Users]] as const).map(([id, label, Icon]) => <button className={tab === id ? 'active' : ''} key={id} onClick={() => { setTab(id); if (id === 'code' && !code && members[0]) void run(() => loadCode(members[0].id)); }}><Icon size={14} />{label}</button>)}</div><label className="revision-select"><History size={13} /><select aria-label="설명 버전" value={revision?.id || ''} onChange={e => { setRevisionId(e.target.value); setSelected([]); setBlockId(''); }}>{revisions.length ? revisions.map(r => <option key={r.id} value={r.id}>v{r.number}{r.id === system.revision?.id ? ' · 최신' : ''} · {r.source === 'ai' ? 'AI 설명' : '구조 메모'}</option>) : revision && <option value={revision.id}>v{revision.number}</option>}</select></label></div>
      <div className="workspace-scroll">{revision?.stale && <div className="inline-warning"><Info size={16} /><span>이전 설정 또는 설명 버전입니다. 현재 설정의 최신 설명을 확인해주세요.</span></div>}
        {tab === 'story' && revision && <><div className="explanation-intro"><div className="intro-label"><Sparkles size={15} /><strong>{revision.source === 'ai' ? '코드 근거를 바탕으로 작성한 AI 초안' : '코드에서 먼저 살펴본 구조 메모'}</strong></div><p>{revision.document.summary}</p>{<div className="ai-callout"><span>{revision.source === 'ai' ? '사용한 방식과 이유를 짧은 회고로 다시 정리합니다. 이전 버전은 남아 있어요.' : aiEnabled ? 'AI가 코드를 읽고 사용한 방식과 핵심 구현을 짧은 회고로 정리합니다.' : 'AI 연결이 준비되면 사용한 방식과 핵심 구현을 회고로 정리합니다.'}</span><button className="button small" disabled={busy || !aiEnabled || revision.id !== system.revision?.id} title={!aiEnabled ? '서버의 AI 연결이 필요합니다.' : ''} onClick={() => void run(async () => { const res = await api<{ job: Job }>(`${base}/generate`, 'POST'); setJob(res.job); })}><Sparkles size={13} />{revision.source === 'ai' ? 'AI 설명 다시 쓰기' : 'AI 설명 생성'}</button></div>}</div>
          <article className="explanation">{revision.document.blocks.map((block, index) => <section className={`explanation-block ${blockId === block.block_id ? 'commenting' : ''}`} key={block.block_id}><div className="block-heading"><span className="block-index">{String(index + 1).padStart(2, '0')}</span><h2>{block.title}</h2><button className="block-comment" title="이 문단에 코멘트" aria-label={`${block.title}에 코멘트`} onClick={() => { setBlockId(block.block_id); draft.current?.focus(); }}><MessageSquare size={14} /><Plus size={10} /></button></div><div className="block-prose">{block.text.split(/\n\s*\n/).map((paragraph, i) => <p key={i}>{paragraph}</p>)}</div><div className="evidence-list">{block.claim_ids.map(cid => { const claim = revision.document.claims.find(c => c.claim_id === cid); if (!claim) return null; return <details className="claim" key={cid}><summary><span className={`basis-tag ${claim.basis}`}>{basisLabels[claim.basis] || '확인 필요'}</span><span className="claim-statement">{claim.statement}</span>{claim.status !== 'supported' && <span className="warning-tag">확인 필요</span>}<ChevronRight size={12} /></summary><div className="claim-sources">{claim.evidence_ids.map(eid => { const evidence = revision.evidence[eid]; if (!evidence) return null; return <button key={eid} className="evidence-link" onClick={() => void run(() => inspect(evidence))}>{evidence.kind === 'code' ? <FileCode2 size={13} /> : <MessageSquare size={13} />}<span>{evidence.kind === 'code' ? `${evidence.path?.split('/').pop()} : ${evidence.start_line}–${evidence.end_line}` : evidence.kind === 'comment' ? '사용자 코멘트 확인' : evidence.kind === 'history' ? `커밋 ${evidence.sha?.slice(0, 7)}` : '사용자 담당 설정'}</span><ArrowRight size={12} /></button>; })}{!claim.evidence_ids.length && <span className="muted">직접 확인된 근거가 없는 추정입니다.</span>}</div></details>; })}</div></section>)}</article>
          {!!revision.document.open_questions.length && <div className="open-questions"><MessageSquare size={17} /><div><h3>경험을 더해주면 좋은 부분</h3>{revision.document.open_questions.map((q, i) => <p key={i}>{q}</p>)}</div></div>}
          {reference && <section className="code-reference"><div className="section-heading"><h2><Code2 size={15} />근거 확인</h2><button className="icon-button" aria-label="근거 닫기" onClick={() => setReference(null)}><X size={16} /></button></div>{reference.kind === 'code' && code ? <CodeView code={code} reference={reference} load={(start) => void run(() => loadCode(code.id, start))} /> : reference.kind === 'comment' ? <p className="reference-text">{reference.text}</p> : reference.kind === 'history' ? <a className="evidence-link" href={`${project.repo_url}/commit/${reference.sha}`} target="_blank" rel="noreferrer">GitHub 커밋 확인<ExternalLink size={14} /></a> : <p className="reference-text">현재 기준 계정: {project.github_username}. 담당 범위 화면에서 사용자가 직접 지정한 정보입니다.</p>}</section>}
          <div className="explanation-footer"><ShieldNote /> <span>{revision.model || 'C# 구문 분석'} · v{revision.number}</span></div>
        </>}
        {tab === 'code' && <div className="code-page"><label className="code-file-select">코드 파일<select value={code?.id || ''} onChange={e => { setReference(null); void run(() => loadCode(e.target.value)); }}>{!code && <option value="">파일 선택</option>}{members.map(f => <option value={f.id} key={f.id}>{f.path}</option>)}</select></label>{code ? <CodeView code={code} load={start => void run(() => loadCode(code.id, start))} /> : <div className="empty-state small">파일을 선택해 코드를 확인해주세요.</div>}</div>}
        {tab === 'ownership' && <div className="ownership-page"><div className="inline-info"><Info size={17} /><p>담당 힌트는 작성자를 확정하지 않습니다. 코드 스타일과 폴더를 확인한 뒤 분석 범위에서 실제 담당을 지정해주세요.</p></div><h2>이 시스템의 파일</h2>{members.map(f => <div className="ownership-file" key={f.id}><FileCode2 size={17} /><div><strong>{f.path.split('/').pop()}</strong><p>{f.namespaces.join(', ') || '네임스페이스 미지정'} · {f.symbol_count}개 선언</p><small>{project.scope.attribution[f.id]?.note}</small></div><span className="tag">{ownershipLabels[project.scope.attribution[f.id]?.status || 'unknown']}</span></div>)}<h2>저장소 최근 이력에서 확인한 계정</h2><p className="muted">고정된 커밋 이전 최대 30건의 저장소 이력입니다. 이 시스템의 단독 담당이나 전체 기여도와 일치하지 않을 수 있습니다.</p>{!history.length && <p className="muted">현재 확인할 수 있는 이력이 없습니다.</p>}{history.slice(0, 12).map(h => <a className="history-row" href={`${project.repo_url}/commit/${h.sha}`} target="_blank" rel="noreferrer" key={h.sha}><GitCommitHorizontal size={16} /><div><strong>{h.message.split('\n')[0]}</strong><span>{h.author_login || `${h.author_name} · 계정 미연결`} · {h.date.slice(0, 10)}</span></div><code>{h.sha.slice(0, 7)}</code><ExternalLink size={12} /></a>)}</div>}
      </div>
    </section>
    <aside className="comments-panel"><div className="sidebar-heading"><h2><MessageSquare size={16} />내 코멘트</h2><span>{activeComments.length}</span></div><div className="comment-intro"><h3>기억나는 내용을 더해주세요.</h3><p>내가 맡은 부분, 개발 의도, 강조하고 싶은 점을 남겨 설명의 방향을 잡아보세요.</p></div><div className="comment-list">{!activeComments.length && <div className="comments-empty"><MessageSquare size={23} /><p>이 설명에 아직 코멘트가 없어요.</p><span>“이 부분은 새 기계를 쉽게 추가하려고<br />데이터와 동작을 나눴어요.”</span></div>}{comments.map(c => <article className={`comment-card ${c.base_revision_id !== revision?.id ? 'past-comment' : ''}`} key={c.id}><div className="comment-meta"><label className="checkbox-label"><input type="checkbox" aria-label="설명에 반영할 코멘트 선택" checked={selected.includes(c.id)} disabled={busy || c.base_revision_id !== revision?.id || !current} onChange={e => setSelected(old => e.target.checked ? [...old, c.id] : old.filter(id => id !== c.id))} /><strong>나</strong></label><span>{commentKinds[c.kind]}</span><button className="icon-button" title="코멘트 수정" aria-label="코멘트 수정" disabled={busy} onClick={() => { setEditComment(c); setEditText(c.text); }}><Pencil size={12} /></button></div>{c.block_id && <div className="comment-target"><BookOpen size={11} />{revision?.document.blocks.find(b => b.block_id === c.block_id)?.title || '특정 문단'}</div>}{editComment?.id === c.id ? <div className="edit-comment"><textarea value={editText} maxLength={4000} onChange={e => setEditText(e.target.value)} aria-label="수정할 코멘트" /><div><button className="text-button" disabled={busy} onClick={() => void run(async () => { await api(`${base}/comments/${c.root_id}`, 'PATCH', { expected_version: c.version, text: editText || c.text, deleted: true }); const res = await api<{ comments: Comment[] }>(`${base}/comments`); setComments(res.comments); setEditComment(null); })}>삭제</button><button className="text-button" onClick={() => setEditComment(null)}>취소</button><button className="button small" disabled={busy || !editText.trim()} onClick={() => void run(async () => { await api(`${base}/comments/${c.root_id}`, 'PATCH', { expected_version: c.version, text: editText, deleted: false }); const res = await api<{ comments: Comment[] }>(`${base}/comments`); setComments(res.comments); setSelected([]); setEditComment(null); })}>저장</button></div></div> : <p>{c.text}</p>}<div className="comment-bottom"><span>{new Date(c.created_at * 1000).toLocaleDateString('ko-KR')} · 코멘트 v{c.version}</span>{revision?.comment_ids.includes(c.id) ? <span className="applied"><Check size={11} />반영됨</span> : c.base_revision_id !== revision?.id ? <span>이전 설명</span> : <span>저장됨</span>}</div></article>)}</div>
      <div className="comment-composer">{blockId && <div className="compose-target"><BookOpen size={12} /><span>{revision?.document.blocks.find(b => b.block_id === blockId)?.title}</span><button className="icon-button" aria-label="문단 지정 해제" onClick={() => setBlockId('')}><X size={12} /></button></div>}<label className="composer-kind">코멘트 유형<select value={kind} onChange={e => setKind(e.target.value)}>{Object.entries(commentKinds).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><textarea ref={draft} aria-label="코멘트 내용" placeholder="실제 개발 경험을 알려주세요.&#10;저장한 뒤 선택해서 설명에 반영할 수 있어요." maxLength={4000} value={comment} onChange={e => setComment(e.target.value)} disabled={busy || !revision} /><div className="compose-footer"><span>{comment.length}/4,000</span><button className="button small" disabled={busy || !comment.trim() || !revision} onClick={() => void run(async () => { const res = await api<{ comment: Comment }>(`${base}/comments`, 'POST', { base_revision_id: revision!.id, block_id: blockId || null, text: comment, kind }); setComments(old => [...old, res.comment]); setSelected(old => [...old, res.comment.id]); setComment(''); setBlockId(''); notify('코멘트를 저장했습니다. 선택한 코멘트를 설명에 반영할 수 있습니다.'); })}><Send size={12} />코멘트 저장</button></div><button className="button primary full apply-button" disabled={busy || !aiEnabled || !allowedIds.length || !current} onClick={() => void run(async () => { const res = await api<{ job: Job }>(`${base}/revise`, 'POST', { base_revision_id: revision!.id, comment_ids: allowedIds }); setJob(res.job); })}><Sparkles size={14} />선택한 코멘트 {allowedIds.length ? `${allowedIds.length}개 ` : ''}반영</button><p className="micro-copy">{aiEnabled ? '기존 설명은 보존하고 새 버전으로 저장합니다.' : '코멘트는 저장할 수 있습니다. AI 반영은 연결 후 사용할 수 있어요.'}</p></div>
    </aside>
    {editSystem && <SystemEditor system={system} files={files.filter(f => project.scope.selected_file_ids.includes(f.id))} busy={busy} run={run} close={() => setEditSystem(false)} save={async (name, ids) => { await api(base, 'PATCH', { expected_version: system.version, name, file_ids: ids }); await refresh(); setEditSystem(false); notify('시스템 구성을 변경했습니다. 설명을 다시 확인해주세요.'); }} />}
  </main>;
}

function ShieldNote() { return <span><Info size={12} />AI의 해석과 실제 개발 의도는 다를 수 있습니다.</span>; }
function CodeView({ code, reference, load }: { code: Code; reference?: Evidence; load: (start: number) => void }) {
  return <div className="code-view"><div className="code-toolbar"><FileCode2 size={14} /><span title={code.path}>{code.path}</span><code>{code.commit_sha.slice(0, 7)}</code>{reference?.url && <a href={reference.url} aria-label="GitHub에서 코드 보기" target="_blank" rel="noreferrer"><ExternalLink size={14} /></a>}</div><div className="code-lines" tabIndex={0}>{code.content.split('\n').map((line, index) => <div className={`code-line ${reference && code.start_line + index <= (reference.end_line || 0) ? 'highlighted' : ''}`} key={code.start_line + index}><span className="line-number">{code.start_line + index}</span><code>{line || ' '}</code></div>)}</div><div className="code-pagination"><button className="icon-button" title="이전 코드" aria-label="이전 코드" disabled={code.start_line <= 1} onClick={() => load(Math.max(1, code.start_line - 120))}><ArrowLeft size={14} /></button><span>{code.start_line}–{code.end_line} / {code.line_count}줄</span><button className="icon-button" title="다음 코드" aria-label="다음 코드" disabled={code.end_line >= code.line_count} onClick={() => load(code.end_line + 1)}><ArrowRight size={14} /></button></div></div>;
}
function SystemEditor({ system, files, busy, run, close, save }: { system: System; files: SourceFile[]; busy: boolean; run: RunAction; close: () => void; save: (name: string, ids: string[]) => Promise<void> }) {
  const [name, setName] = useState(system.name); const [ids, setIds] = useState(system.file_ids); const [search, setSearch] = useState(''); const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { dialog.current?.showModal(); }, []);
  return <dialog ref={dialog} className="modal system-modal" onCancel={close}><form onSubmit={e => { e.preventDefault(); void run(() => save(name, ids)); }}><div className="section-heading"><h2>시스템 구성 수정</h2><button type="button" className="icon-button" onClick={close} aria-label="닫기"><X size={18} /></button></div><label>시스템 이름<input value={name} onChange={e => setName(e.target.value)} required maxLength={200} /></label><label>파일 검색<input value={search} onChange={e => setSearch(e.target.value)} placeholder="이 시스템에 포함할 파일" /></label><div className="system-file-options">{files.filter(f => f.path.toLowerCase().includes(search.toLowerCase())).map(f => <label className="checkbox-label" key={f.id}><input type="checkbox" checked={ids.includes(f.id)} onChange={e => setIds(old => e.target.checked ? [...old, f.id] : old.filter(id => id !== f.id))} /><span>{f.path}</span></label>)}</div><p className="micro-copy">하나의 파일을 여러 시스템에서 참고할 수 있습니다. 설명 버전은 이전 구성과 구분됩니다.</p><div className="modal-actions"><span>{ids.length}개 파일</span><button type="button" className="button" onClick={close}>취소</button><button className="button primary" disabled={busy || !name.trim() || !ids.length}>시스템 저장</button></div></form></dialog>;
}
